# Docs:
# https://yazi-rs.github.io/docs/configuration/overview#mixing
# Defaults:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

# `prepend_` assigns the entry higher priority than the default
[mgr]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
  { on = "l", run = "shell --block lazygit", desc = "Run lazygit" },
  { on = "q", run = "close", desc = "Close the current tab, or quit if it's last" },
  { on = "<C-c>", run = "escape", desc = "Exit visual mode, clear selection, or cancel search" },
  { on = "<S-c>", run = "shell --orphan 'code -a \"$0\" \"$@\"'", desc = "Open selected objects in current VSCode workspace" },
]

[tasks]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
]

[spot]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
]

[pick]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
  { on = "<S-a>", run = "shell 'code {}'", desc = "Append selected items to VSCode workspace" },
]

[confirm]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Open help" },
]
